### ISSUE TITLE
Filename other than handler.so

### ISSUE THREAD

**Issue by danilobuerger** [eawsy/aws-lambda-go#5]
Is it possible to somehow use a different filename other than handler.so?

If I want to provision the lambda first with cloudformation, I could use something like:

```
Lambda:
  Type: AWS::Lambda::Function
  Properties:
    Runtime: python2.7
    Handler: index.handler
    Role: !GetAtt LambdaExecutionRole.Arn
    Code:
      ZipFile: |
        def handler(event, context): return
```

If I now replace the code, I would have to change the handler too.

**Comment by fsenart** [comment]
Hi,

It is not possible to change the binary name. It has to be `handler.so` as this name is [the name of the final low-level Python C extension](https://github.com/eawsy/aws-lambda-go/blob/54c2e1655cf9266c282a4f6c6500668c6978fc04/service/lambda/runtime/proxy.c#L204) used by AWS Lambda.

But, @eawsy we use CloudFormation all the time and here is an example of snippet to deploy Lambda functions build with this project:

``` yaml
Lambda:
  Type: AWS::Lambda::Function
  Properties:
    Code:
      S3Bucket: you_s3_bucket
      S3Key: handler.zip  # <===== package containing handle.so
    Role: !GetAtt [LambdaExecutionRole, Arn]
    Handler: handler.handle
    Runtime: python2.7
    MemorySize: 128
    Timeout: 1
```

What you are doing with your CloudFormation is inlining your code in the CF template. This is [only possible with script languages](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-code.html#cfn-lambda-function-code-zipfile) as languages like Go (or even the officially supported Java) need a compilation step.

More generally, independently from your request, I don't encourage you to inline your business code in the CloudFormation template.
